
---
apiVersion: cluster.atom.io/v1alpha1
kind: Nucleon
metadata:
  name: nucleon
spec:
  nucleus:
    enable: true
    registry:
      docker_registry:
        port: 6447
    ci:
      tekton: {}
    ingress:
      traefik: {}
  apiserver:
    enable: true
    monitoring:
      prometheus:
        replicas: 1
    alerting:
      alert_manager:
        replicas: 1
    logging:
      loki:
        replicas: 1
  cluster_manager:
    enable: true
    storage:
      openebs:
        device: "/dev/sadx"
    autoscaler:
      cluster_autoscaler:
        cloud_provider: atom
    agents:
      spot_instance: {}
  addons:
    - name: mysql-operator
      namespace: addons
      chart:
        name: mysql-operator
        repo: https://presslabs.github.io/charts
    - name: rabbitmq-operator
      namespace: rabbitmq-system
      yaml:
        paths:
          - https://github.com/rabbitmq/cluster-operator/releases/download/v1.7.0/cluster-operator.yml
    - name: redis-operator
      namespace: default
      yaml:
        paths:
          - https://raw.githubusercontent.com/spotahome/redis-operator/master/example/operator/all-redis-operator-resources.yaml
